#!/bin/sh /etc/rc.common

START=18
USE_PROCD=1

start_service() {
	[ ! -s /etc/proxyos/port-role-detected ] || return 0
	procd_open_instance
	procd_set_param command /usr/sbin/proxyos-detect-ports
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param respawn 3600 5 0
	procd_close_instance
}

