#!/bin/sh /etc/rc.common

USE_PROCD=1
START=18
STOP=90

start_service() {
	[ -x /usr/sbin/tailscaled ] || return 0
	mkdir -p /etc/tailscale /var/run/tailscale
	procd_open_instance
	procd_set_param command /usr/sbin/tailscaled \
		--state=/etc/tailscale/tailscaled.state \
		--socket=/var/run/tailscale/tailscaled.sock \
		--port=41641
	procd_set_param respawn 3600 5 5
	procd_set_param limits nofile="1048576 1048576"
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger tailscale
}
